<footer>
        <div class="izq-footer">
            <a href="https://wa.me/2494553418" target="_blank"><img src="img/whatsapp.png" alt="Link a whatsapp"></a>
            <a href="https://www.instagram.com/oneshine.tandil/" target="_blank"><img src="img/instagram.png" alt="Link a instagram"></a>
        </div>

        <div class="der-footer">
            <h4>One Shine</h4>
            <p>Liniers 1320, Tandil, <br>Buenos Aires, Argentina</p>
        </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>