<?php 
require_once './templates/header.phtml'
?>

<form action="addProducto" method="post" class="text-center w-50 mx-auto mt-5 mb-5">
<h3 class="text-success w-30 mx-auto text-center mt-5">Agregar un Producto</h3>
  <div class="mb-3">
    <label for="formGroupExampleInput" class="form-label">Nombre</label>
    <input type="text" class="form-control text-center" id="formGroupExampleInput" name="nombre" >
  </div>
  <div class="mb-3">
    <label for="formGroupExampleInput2" class="form-label">Cantidad</label>
    <input type="text" class="form-control text-center" id="formGroupExampleInput2" name="cantidad" >
  </div>
  <div class="mb-3">
    <label for="formGroupExampleInput2" class="form-label">Descripcion</label>
    <input type="text" class="form-control text-center" id="formGroupExampleInput2" name="descripcion">
  </div>
  <div class="mb-3">
    <label for="formGroupExampleInput2" class="form-label">Precio</label>
    <input type="number" class="form-control text-center" id="formGroupExampleInput2" name="precio"> 
  </div>
  <div class="mb-3">
    <select name="categoria" class="form-select text-center" aria-label="Default select example"> 
        <?php foreach($categorias as $categoria): ?>
          <option value ="<?= $categoria->id_categoria?>"><?= $categoria->nombreCat ?></option>
        <?php endforeach ?>
    </select>
    </div>
 <button type="submit" class="btn btn-success">Añadir</button>
</form>

<?php 
    require_once './templates/footer.phtml'
?>